using HumanResourceManagement.Domain.Repositories;

namespace HumanResourceManagement.Infrastructure.Persistence.Repositories;

public class EmployeeReviewFromManagerWithQuestionAndAnswersRepository : IEmployeeReviewFromManagerWithQuestionAndAnswersRepository
{
}
